### ISSUE TITLE
Problem with distinctCount and apostrophe-db-mongo-3-driver

### ISSUE THREAD

**Issue by GiuseppeCM** [apostrophecms/apostrophe-db-mongo-3-driver#2] opened 2019-04-02 14:02 UTC
When the module is activated, and you try to do a distinctCount in a cursor, an error return and the server goes down.

Looking through the code I discovered that: in /apostrophe-docs/lib/cursor at line 994 (function toDistinct), have a function distinctCounts and in it have self.db.aggregate(pipeline, function(err, results) { ..... }, the result without mongo-3-driver is correct, but with the driver, results is a AggregationCursor, and to have the results json, would do results.toArray(callback).
This kind of behavior is present only with the mmongo-3-driver

**Comment by abea** [comment] 2020-05-26 21:56
CC @boutell

**Comment by boutell** [comment] 2020-05-28 17:55
Since this module is designed to let you use the mongodb 3.x driver natively in apostrophe projects **following mongodb 3.x driver's calling conventions**, we can't introduce a bc break by wrapping it for mongodb 2.x behavior where it is incompatible.

And indeed that would be pointless since apostrophe core now ships with `emulate-mongo-2-driver`, which already provides the 3.x driver wrapped to behave **as if it were the 2.x driver**.

But, we do have customers who are committed to `apostrophe-db-mongo-3-driver` because writing mongodb 3.x driver code is what they actually want to do.

So to address the bug you point out, we will need to update `cursor.js` in apostrophe core to check whether `results` has a toArray method and invoke it if necessary. That way it will work with *either* this module, or the 2.x emulation wrapper that ships with apostrophe.

Closing this because it's not a bug in this module, but I've referenced it here since it is a bug in apostrophe itself:

https://github.com/apostrophecms/apostrophe/issues/2215

**Closed as completed by boutell** 2020-05-28 17:55 UTC
